/**
 * Configuration helper functions for book.config.ts
 */

import type { BookConfig } from "../types";
import type {
  UserConfig,
  ResolvedConfig,
  ConfigExport,
  MarkdownPlugin,
  CSSPlugin,
  ImagePlugin,
  ValidatorFactory,
} from "./types";

/**
 * Define a book configuration with type safety and IDE support.
 *
 * @example
 * ```ts
 * // book.config.ts
 * import { defineConfig } from "@swibostyle/core";
 *
 * export default defineConfig({
 *   title: "My Book",
 *   authors: [{ name: "Author", role: "aut" }],
 *   publisher: "Publisher",
 *   lang: "ja",
 *   bookId: { epub: "urn:uuid:..." },
 *
 *   // Plugin configuration
 *   vfm: {
 *     hardLineBreaks: true,
 *   },
 *
 *   // Validators
 *   validators: [
 *     () => createEpubCheckValidator(),
 *     () => createCustomValidator(),
 *   ],
 * });
 * ```
 */
export function defineConfig(config: UserConfig): UserConfig {
  return config;
}

/**
 * Create a markdown plugin
 *
 * @example
 * ```ts
 * const myPlugin = defineMarkdownPlugin({
 *   name: "my-plugin",
 *   beforeProcess(content) {
 *     return content.replace(/foo/g, "bar");
 *   },
 * });
 * ```
 */
export function defineMarkdownPlugin(plugin: MarkdownPlugin): MarkdownPlugin {
  return plugin;
}

/**
 * Create a CSS plugin
 *
 * @example
 * ```ts
 * const myPlugin = defineCSSPlugin({
 *   name: "my-css-plugin",
 *   afterProcess(output) {
 *     return {
 *       ...output,
 *       css: output.css + "\n/* Generated by swibostyle *\/",
 *     };
 *   },
 * });
 * ```
 */
export function defineCSSPlugin(plugin: CSSPlugin): CSSPlugin {
  return plugin;
}

/**
 * Create an image plugin
 *
 * @example
 * ```ts
 * const myPlugin = defineImagePlugin({
 *   name: "my-image-plugin",
 *   afterProcess(data, path) {
 *     console.log(`Processed image: ${path}`);
 *     return data;
 *   },
 * });
 * ```
 */
export function defineImagePlugin(plugin: ImagePlugin): ImagePlugin {
  return plugin;
}

/**
 * Extract BookConfig from UserConfig
 */
export function extractBookConfig(config: UserConfig): BookConfig {
  return {
    title: config.title,
    titleSortKey: config.titleSortKey,
    authors: config.authors,
    publisher: config.publisher,
    publisherSortKey: config.publisherSortKey,
    lang: config.lang,
    bookId: config.bookId,
    layout: config.layout ?? "reflowable",
    pageDirection: config.pageDirection ?? "ltr",
    primaryWritingMode: config.primaryWritingMode ?? "horizontal-tb",
    orientation: config.orientation,
    spread: config.spread,
    cover: config.cover,
    bookType: config.bookType,
    originalResolution: config.originalResolution,
    targets: config.targets,
  };
}

/**
 * Resolve user configuration with defaults applied
 */
export function resolveConfig(config: UserConfig): ResolvedConfig {
  return {
    book: extractBookConfig(config),
    adapters: config.adapters ?? {},
    vfm: {
      hardLineBreaks: true,
      partial: true,
      ...config.vfm,
    },
    markdownPlugins: config.markdownPlugins ?? [],
    cssPlugins: config.cssPlugins ?? [],
    imagePlugins: config.imagePlugins ?? [],
    hooks: config.hooks ?? {},
    validators: config.validators ?? [],
    skipValidation: config.skipValidation ?? false,
  };
}

/**
 * Resolve configuration export (handles function exports)
 */
export async function resolveConfigExport(configExport: ConfigExport): Promise<ResolvedConfig> {
  const config = typeof configExport === "function" ? await configExport() : configExport;
  return resolveConfig(config);
}

/**
 * Chain multiple validators into one
 *
 * @example
 * ```ts
 * const chainedValidator = chainValidators([
 *   createEpubCheckValidator(),
 *   createCustomValidator(),
 * ]);
 * ```
 */
export function chainValidators(factories: ValidatorFactory[]): ValidatorFactory {
  return async () => {
    const validators = await Promise.all(factories.map((f) => f()));

    return {
      name: `chain(${validators.map((v) => v.name).join(", ")})`,
      async validate(epubPath, options) {
        const allErrors: import("./types").ValidationMessage[] = [];
        const allWarnings: import("./types").ValidationMessage[] = [];
        const allInfos: import("./types").ValidationMessage[] = [];

        for (const validator of validators) {
          const result = await validator.validate(epubPath, options);
          allErrors.push(...result.errors);
          allWarnings.push(...result.warnings);
          if (result.infos) {
            allInfos.push(...result.infos);
          }
        }

        return {
          valid: allErrors.length === 0,
          errors: allErrors,
          warnings: allWarnings,
          infos: options?.includeInfos ? allInfos : undefined,
        };
      },
    };
  };
}
